### ISSUE TITLE
Support for requirements.txt (Python)

### ISSUE THREAD

**Issue by matrixik** [BrainMaestro/packagehub#6]
I'm not sure how much effort it would need but would be nice to have support also for requirements.txt files beside Pipfile (I learned about Pipfile from this repo, thx).

Files to look:
```
requirements.txt
test-requirements.txt
```

Example:
https://github.com/openstack/monasca-agent/blob/master/requirements.txt

**Comment by BrainMaestro** [comment]
Hey @matrixik, I opted for Pipfile because the spec is easier to understand and parse. `requirements.txt` looked quite permissive and confusing to me. I would welcome an implementation though. Is it something you would be interested in doing?

Oh and thanks for taking the time to open issues with examples and clear information. I really appreciate it.

**Comment by BrainMaestro** [comment]
Hey @matrixik, so are you interested in implementing this? If not, I think we should close the issue

**Comment by matrixik** [comment]
Hi, no time to look into it, sorry.
